version: '3'
services:
  julia:
    image: myspace
    container_name: myspace-julia
    volumes:
      - ./:/work
    working_dir: /work
    command: julia -J /sysimages/ijulia.so --project=/work
  web:
    image: myspace
    container_name: myspace-packagedocs
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - "8000:8000"
    command: make web
